"""Traducciones del juego (generadas a partir de los textos en español). Clave: texto en español."""

CA = {
    "LOGROS": "ASSOLIMENTS",
    "LOGRO DESBLOQUEADO": "ASSOLIMENT DESBLOQUEJAT",
    "Logro secreto": "Assoliment secret",
    "Placa {n}/{t}": "Placa {n}/{t}",
    "Saltar  >>": "Saltar  >>",
    "Bronce 50 · Plata 150 · Oro 400 · Platino 1000 monedas": "Bronze 50 · Plata 150 · Or 400 · Platí 1000 monedes",
    "Bronce": "Bronze",
    "Plata": "Plata",
    "Oro": "Or",
    "Platino": "Platí",
    "Primer contacto": "Primer contacte",
    "Completa el escenario 1-1.": "Completa l'escenari 1-1.",
    "Las ruinas son nuestras": "Les ruïnes són nostres",
    "Derrota al General Xylothian.": "Derrota el General Xylothian.",
    "Poda radical": "Poda radical",
    "Derrota al Maestro de la Selva.": "Derrota el Mestre de la Selva.",
    "Sin voz": "Sense veu",
    "Derrota al Comandante Supremo.": "Derrota el Comandant Suprem.",
    "Fuera de órbita": "Fora d'òrbita",
    "Destruye la Nave Nodriza.": "Destrueix la Nau Nodrissa.",
    "Silencio": "Silenci",
    "Apaga el Núcleo de Xylos y termina la historia.": "Apaga el Nucli de Xylos i acaba la història.",
    "Hasta el final": "Fins al final",
    "Mira la cinemática final entera sin saltarla.": "Mira la cinemàtica final sencera sense saltar-la.",
    "Intocable": "Intocable",
    "Derrota a un jefe sin recibir ni un golpe.": "Derrota un cap sense rebre ni un cop.",
    "Contrarreloj": "Contrarellotge",
    "Consigue la estrella de rapidez en 5 escenarios.": "Aconsegueix l'estrella de rapidesa en 5 escenaris.",
    "Constelación": "Constel·lació",
    "Consigue las 45 estrellas.": "Aconsegueix les 45 estrelles.",
    "Veterano de verdad": "Veterà de debò",
    "Derrota al Núcleo de Xylos en Difícil.": "Derrota el Nucli de Xylos en Difícil.",
    "Superviviente": "Supervivent",
    "Llega a la oleada 10 en Supervivencia.": "Arriba a l'onada 10 a Supervivència.",
    "Leyenda de la arena": "Llegenda de l'arena",
    "Llega a la oleada 20 en Supervivencia.": "Arriba a l'onada 20 a Supervivència.",
    "Exterminador": "Exterminador",
    "Elimina a 500 alienígenas.": "Elimina 500 alienígenes.",
    "Acróbata": "Acròbata",
    "Haz 100 volteretas.": "Fes 100 tombarelles.",
    "Por la espalda": "Per l'esquena",
    "Elimina a un escudero disparándole por detrás.": "Elimina un escuder disparant-li per darrere.",
    "Carambola": "Carambola",
    "Haz que la explosión de un kamikaze elimine a otro alienígena.": "Fes que l'explosió d'un kamikaze elimini un altre alienígena.",
    "Arsenal completo": "Arsenal complet",
    "Consigue las cinco armas.": "Aconsegueix les cinc armes.",
    "Al máximo": "Al màxim",
    "Sube todas las mejoras al máximo.": "Puja totes les millores al màxim.",
    "Todo de oro": "Tot d'or",
    "Equípate el uniforme y el aspecto de arma dorados.": "Equipa't l'uniforme i l'aspecte d'arma daurats.",
    "Placa encontrada": "Placa trobada",
    "Encuentra una placa de identificación escondida.": "Troba una placa d'identificació amagada.",
    "Hay cosas brillando donde nadie mira.": "Hi ha coses que brillen on ningú no mira.",
    "Nadie se queda atrás": "Ningú no es queda enrere",
    "Recupera las cinco placas de identificación escondidas.": "Recupera les cinc plaques d'identificació amagades.",
    "Los soldados caídos dejaron algo en cada sector.": "Els soldats caiguts van deixar alguna cosa a cada sector.",
    "Ojo por ojo": "Ull per ull",
    "Revienta el ojo de la torre de vigilancia del escenario 1-1.": "Rebenta l'ull de la torre de vigilància de l'escenari 1-1.",
    "Alguien te vigila desde el fondo del primer escenario.": "Algú et vigila des del fons del primer escenari.",
    "Avistamiento": "Albirament",
    "Derriba uno de los ovnis que cruzan el cielo del fondo.": "Abat un dels ovnis que creuen el cel del fons.",
    "Mira al cielo.": "Mira el cel.",
    "Vieja escuela": "Vella escola",
    "Derrota al Núcleo de Xylos usando solo la pistola.": "Derrota el Nucli de Xylos només amb la pistola.",
    "A veces, menos es más.": "De vegades, menys és més.",
    "Código secreto": "Codi secret",
    "Introduce el código más famoso de los videojuegos en el menú.": "Introdueix el codi més famós dels videojocs al menú.",
    "Arriba, arriba...": "Amunt, amunt...",
    "Mal cálculo": "Mal càlcul",
    "Muere por la explosión de un kamikaze.": "Mor per l'explosió d'un kamikaze.",
    "No los abraces.": "No els abracis.",
    "Héroe de la galaxia": "Heroi de la galàxia",
    "Consigue todos los demás logros.": "Aconsegueix tots els altres assoliments.",
    "Armas": "Armes",
    "Aspecto": "Aspecte",
    "+20 VIDA": "+20 VIDA",
    "{n} monedas": "{n} monedes",
    "+10 vida · ¡prepárate!": "+10 vida · prepara't!",
    "+15% de daño con todas las armas": "+15% de dany amb totes les armes",
    "+20 de vida máxima por nivel": "+20 de vida màxima per nivell",
    "+30% de munición máxima": "+30% de munició màxima",
    "+{m} monedas · +{x} XP": "+{m} monedes · +{x} XP",
    "1-5 / Q / rueda": "1-5 / Q / roda",
    "< Menú": "< Menú",
    "< Volver": "< Tornar",
    "A / D  o  flechas": "A / D  o  fletxes",
    "ALIENÍGENA": "ALIENÍGENA",
    "ARENA": "ARENA",
    "ARMA": "ARMA",
    "Activar / silenciar el sonido": "Activar / silenciar el so",
    "Ahí está el General. Derríbalo y el sector norte será nuestro.": "Allà hi ha el General. Abat-lo i el sector nord serà nostre.",
    "Al otro lado del portal, un planeta de cielo violeta. Los restos de la Nave Nodriza revelaron la verdad: todos los Xylothians obedecen a una sola mente, el Núcleo de Xylos. Y está aquí.": "A l'altra banda del portal, un planeta de cel violeta. Les restes de la Nau Nodrissa van revelar la veritat: tots els Xylothians obeeixen una sola ment, el Nucli de Xylos. I és aquí.",
    "Al sur, donde había bosques, ahora crece la Selva Tecnológica: plantas y máquinas fusionadas. Los Xylothians no construyen, cultivan. Y están cultivando la Tierra.": "Al sud, on hi havia boscos, ara creix la Selva Tecnològica: plantes i màquines fusionades. Els Xylothians no construeixen, cultiven. I estan cultivant la Terra.",
    "Algunas mejoras se abren al avanzar en la historia.": "Algunes millores s'obren en avançar en la història.",
    "Aquí tus armas no sirven. Aquí solo existo yo.": "Aquí les teves armes no serveixen. Aquí només existeixo jo.",
    "Arcoíris": "Arc iris",
    "Arena": "Arena",
    "Arma bloqueada aquí: {a} · Equipada: {b}": "Arma bloquejada aquí: {a} · Equipada: {b}",
    "Arte nuevo e intro": "Art nou i intro",
    "Aspecto de arma {a}": "Aspecte d'arma {a}",
    "Atrae los objetos desde más lejos": "Atrau els objectes des de més lluny",
    "Atraviesa a los enemigos. Tecnología Xylothian.": "Travessa els enemics. Tecnologia Xylothian.",
    "Atraviesa a los enemigos. Tecnología Xylothian. Disponible al completar 4-2.": "Travessa els enemics. Tecnologia Xylothian. Disponible en completar el 4-2.",
    "Auto": "Auto",
    "Automático y preciso.": "Automàtic i precís.",
    "AÑO 2139": "ANY 2139",
    "AÑO 2147": "ANY 2147",
    "Año 2139. Una noche, el cielo de la Tierra se abre: decenas de portales de luz violeta aparecen sobre las ciudades.": "Any 2139. Una nit, el cel de la Terra s'obre: desenes de portals de llum violeta apareixen sobre les ciutats.",
    "Año 2147. Nexus despierta en un búnker bajo la ciudad. La humanidad ya no tiene a nadie más. Su misión: llegar hasta el corazón de la invasión.": "Any 2147. Nexus es desperta en un búnquer sota la ciutat. La humanitat ja no té ningú més. La seva missió: arribar fins al cor de la invasió.",
    "BALAS: {b}/{m}": "BALES: {b}/{m}",
    "BALAS: ∞": "BALES: ∞",
    "BATTLE PASS": "BATTLE PASS",
    "Bajar de una plataforma": "Baixar d'una plataforma",
    "Balas": "Bales",
    "Battle Pass": "Battle Pass",
    "Battle Pass nivel {n}": "Battle Pass nivell {n}",
    "Blindaje": "Blindatge",
    "Bloqueado": "Bloquejat",
    "Borrar progreso": "Esborrar progrés",
    "COMANDANTE DE ÉLITE": "COMANDANT D'ELIT",
    "COMANDANTE SUPREMO": "COMANDANT SUPREM",
    "CRÉDITOS": "CRÈDITS",
    "Cada escenario limita la potencia de las armas que puedes usar.": "Cada escenari limita la potència de les armes que pots fer servir.",
    "Cambiar de arma": "Canviar d'arma",
    "Campo supresor de la colmena: las armas pesadas no funcionan.": "Camp supressor del rusc: les armes pesants no funcionen.",
    "Cargadores": "Carregadors",
    "Català": "Català",
    "Cazador de aliens": "Caçador d'aliens",
    "Cañón de plasma": "Canó de plasma",
    "Cibernético": "Cibernètic",
    "Clic / ESPACIO para continuar": "Clic / ESPAI per continuar",
    "Clic / ESPACIO para ver todo el texto": "Clic / ESPAI per veure tot el text",
    "Clic izquierdo": "Clic esquerre",
    "Clásico": "Clàssic",
    "Cmdte. Reyes": "Cmdt. Reyes",
    "Completa": "Completa",
    "Completa el sector {n} para leerlo.": "Completa el sector {n} per llegir-lo.",
    "Completa {e}": "Completa {e}",
    "Completado": "Completat",
    "Comprar {c}": "Comprar {c}",
    "Consigue más subiendo de nivel en el Battle Pass.": "Aconsegueix-ne més pujant de nivell al Battle Pass.",
    "Continuar": "Continuar",
    "Créditos": "Crèdits",
    "Cuando un enemigo brilla, va a atacar: ¡apártate o rueda!": "Quan un enemic brilla, és que atacarà: aparta't o rodola!",
    "DESPEGUE": "LLANÇAMENT",
    "Daño": "Dany",
    "De ellos salen los Xylothians, una especie que no piensa: obedece. Todos sus soldados son extensiones de una sola mente.": "D'ells surten els Xylothians, una espècie que no pensa: obeeix. Tots els seus soldats són extensions d'una sola ment.",
    "Desierto": "Desert",
    "Detente. Únete a nosotros. Deja de luchar.": "Atura't. Uneix-te a nosaltres. Deixa de lluitar.",
    "Dibujado con código (tools/)": "Dibuixat amb codi (tools/)",
    "Dificultad": "Dificultat",
    "Dificultad: Normal (se cambia en Opciones)": "Dificultat: Normal (es canvia a Opcions)",
    "Dificultad: {d} (se cambia en Opciones)": "Dificultat: {d} (es canvia a Opcions)",
    "Difícil": "Difícil",
    "Diseño de juego": "Disseny del joc",
    "Disp/s": "Tirs/s",
    "Disparar (mantén: armas automáticas)": "Disparar (mantén: armes automàtiques)",
    "Disponible al completar {e}.": "Disponible en completar {e}.",
    "Dorado": "Daurat",
    "Dra. Vega": "Dra. Vega",
    "EL PORTAL": "EL PORTAL",
    "EL REGRESO": "EL RETORN",
    "ENEMIGOS: {n}": "ENEMICS: {n}",
    "ESPACIO / W / arriba": "ESPAI / W / amunt",
    "ESPACIO / clic: saltar": "ESPAI / clic: saltar",
    "ESPACIO / clic: siguiente  ·  ESC: saltar": "ESPAI / clic: següent  ·  ESC: saltar",
    "Efectos": "Efectes",
    "El Comandante Supremo se desploma sobre la nieve. Con su último aliento, lanza una señal hacia el cielo.": "El Comandant Suprem s'enfonsa sobre la neu. Amb el seu últim alè, llança un senyal cap al cel.",
    "El Guardián. Es lo último que hay entre el Núcleo y yo.": "El Guardià. És l'últim que hi ha entre el Nucli i jo.",
    "El Maestro de la Selva, el bio-constructor que hace crecer esta jungla, protege su corazón. Si cae, la selva dejará de avanzar y la fortaleza quedará al descubierto.": "El Mestre de la Selva, el bioconstructor que fa créixer aquesta jungla, protegeix el seu cor. Si cau, la selva deixarà d'avançar i la fortalesa quedarà al descobert.",
    "El Maestro de la Selva. Y esa plataforma podrida no aguantará mucho.": "El Mestre de la Selva. I aquesta plataforma podrida no aguantarà gaire.",
    "El Núcleo de Xylos": "El Nucli de Xylos",
    "El Núcleo de Xylos abre su ojo inmenso. Miles de años de conquistas, cientos de mundos absorbidos. Hoy, por primera vez, alguien ha llegado hasta aquí. Acaba con esto, Nexus.": "El Nucli de Xylos obre el seu ull immens. Milers d'anys de conquestes, centenars de mons absorbits. Avui, per primera vegada, algú ha arribat fins aquí. Acaba amb això, Nexus.",
    "El Núcleo de Xylos se apaga. Por primera vez en mil años, la colmena queda en silencio.": "El Nucli de Xylos s'apaga. Per primera vegada en mil anys, el rusc queda en silenci.",
    "El que hace crecer la jungla": "El que fa créixer la jungla",
    "El suelo del hangar está cargado. Salta en cuanto veas chispas.": "El terra de l'hangar està carregat. Salta tan bon punt vegis espurnes.",
    "El suelo se rompe bajo tus pies. Como tu especie.": "El terra es trenca sota els teus peus. Com la teva espècie.",
    "En el corazón de la colmena, un campo supresor bloquea las armas pesadas. El Guardián de la Colmena vigila la entrada a la cámara del Núcleo. Solo tus reflejos te llevarán más allá.": "Al cor del rusc, un camp supressor bloqueja les armes pesants. El Guardià del Rusc vigila l'entrada a la cambra del Nucli. Només els teus reflexos et portaran més enllà.",
    "En el puente de mando te espera la Nave Nodriza en persona: una conciencia viva fundida con el metal. Si cae, la flota se quedará sin órdenes y el portal hacia su mundo quedará abierto.": "Al pont de comandament t'espera la Nau Nodrissa en persona: una consciència viva fosa amb el metall. Si cau, la flota es quedarà sense ordres i el portal cap al seu món quedarà obert.",
    "En la Tierra, los portales se cierran uno a uno. Sin su mente, los Xylothians dejan de luchar.": "A la Terra, els portals es tanquen un a un. Sense la seva ment, els Xylothians deixen de lluitar.",
    "En la cima de la fortaleza espera el Comandante Supremo, la voz del enemigo en la Tierra. Si cae, los Xylothians quedarán sin líder... o eso cree Nexus.": "Al cim de la fortalesa espera el Comandant Suprem, la veu de l'enemic a la Terra. Si cau, els Xylothians quedaran sense líder... o això creu Nexus.",
    "En medio de la selva se esconde un laboratorio alienígena lleno de criaturas en tanques. El aire está cargado de gas inflamable: cuidado con lo que disparas.": "Enmig de la selva s'amaga un laboratori alienígena ple de criatures en tancs. L'aire està carregat de gas inflamable: compte amb el que dispares.",
    "En menos de {s} s": "En menys de {s} s",
    "English": "English",
    "Entre los restos se abre un portal: el camino a Xylos, su mundo de origen. Nexus no se lo piensa dos veces.": "Entre les restes s'obre un portal: el camí a Xylos, el seu món d'origen. Nexus no s'ho pensa dues vegades.",
    "Equipa los aspectos en Tienda > Aspecto.": "Equipa els aspectes a Botiga > Aspecte.",
    "Equipada": "Equipada",
    "Equipar": "Equipar",
    "Es él, Nexus: la voz de la mente en la Tierra.": "És ell, Nexus: la veu de la ment a la Terra.",
    "Esas plataformas son chatarra que flota. Calcula bien los saltos.": "Aquestes plataformes són ferralla que flota. Calcula bé els salts.",
    "Escalado": "Escalat",
    "Escopeta": "Escopeta",
    "Escudos de energía: por delante no les haces nada. ¡Rodéalos!": "Escuts d'energia: per davant no els fas res. Envolta'ls!",
    "Esos tanques... están criando soldados. Y las tuberías sueltan gas tóxico.": "Aquests tancs... estan criant soldats. I les canonades deixen anar gas tòxic.",
    "Español": "Español",
    "Especie colectiva originaria del planeta Xylos. Ningún individuo piensa por sí mismo: todos son extensiones de una sola mente. Llegaron a la Tierra en 2139 a través de portales y en ocho años hicieron caer todas las capitales.": "Espècie col·lectiva originària del planeta Xylos. Cap individu pensa per si mateix: tots són extensions d'una sola ment. Van arribar a la Terra el 2139 a través de portals i en vuit anys van fer caure totes les capitals.",
    "Estoy dentro. El suelo del patio está electrificado a trozos.": "Sóc a dins. El terra del pati està electrificat a trossos.",
    "Estrellas: completa el escenario, sin recibir daño y a tiempo.": "Estrelles: completa l'escenari, sense rebre dany i a temps.",
    "Estrellas: {e}/3 · récord de tiempo: {s} s": "Estrelles: {e}/3 · rècord de temps: {s} s",
    "Están cargando el rayo. ¡No hay tiempo!": "Estan carregant el raig. No hi ha temps!",
    "Estándar": "Estàndard",
    "Expediente bloqueado": "Expedient bloquejat",
    "F11: pantalla completa  ·  M: silenciar": "F11: pantalla completa  ·  M: silenciar",
    "FIN": "FI",
    "FIN DE LA PARTIDA": "FI DE LA PARTIDA",
    "Fortaleza": "Fortalesa",
    "Fortaleza Xylothian": "Fortalesa Xylothian",
    "Fusil": "Fusell",
    "Fácil": "Fàcil",
    "GENERAL XYLOTHIAN": "GENERAL XYLOTHIAN",
    "GUARDIÁN DE LA COLMENA": "GUARDIÀ DEL RUSC",
    "GUÍA": "GUIA",
    "Gas inflamable en el laboratorio: nada más potente que la escopeta.": "Gas inflamable al laboratori: res més potent que l'escopeta.",
    "Gráficos originales": "Gràfics originals",
    "Guardián del patio interior": "Guardià del pati interior",
    "Guía": "Guia",
    "HAS CAÍDO": "HAS CAIGUT",
    "HECHO POR NACHO Y ABEL": "FET PER NACHO I ABEL",
    "HISTORIA": "HISTÒRIA",
    "Han soltado tropas en el casco.": "Han deixat anar tropes al casc.",
    "Has caído en combate. Los Xylothians avanzan. ¿Qué harás, Nexus?": "Has caigut en combat. Els Xylothians avancen. Què faràs, Nexus?",
    "Has entrado por las cloacas. Para cruzar el patio interior tendrás que moverte en silencio y eliminar al Comandante de Élite que vigila la segunda línea.": "Has entrat per les clavegueres. Per creuar el pati interior t'hauràs de moure en silenci i eliminar el Comandant d'Elit que vigila la segona línia.",
    "Has superado {o} oleadas y eliminado a {b} enemigos.": "Has superat {o} onades i eliminat {b} enemics.",
    "Haz clic para empezar": "Fes clic per començar",
    "Historia": "Història",
    "Historia desbloqueada: El Núcleo de Xylos": "Història desbloquejada: El Nucli de Xylos",
    "Historia desbloqueada: La Nave Nodriza": "Història desbloquejada: La Nau Nodrissa",
    "Historia desbloqueada: La tecnología viva": "Història desbloquejada: La tecnologia viva",
    "Historia desbloqueada: Los Xylothians": "Història desbloquejada: Els Xylothians",
    "Historia desbloqueada: Proyecto NEXUS": "Història desbloquejada: Projecte NEXUS",
    "Historia desbloqueada: {h}": "Història desbloquejada: {h}",
    "Humano... ¿Por qué no te arrodillas como los demás?": "Humà... Per què no t'agenolles com els altres?",
    "Héroe de la Tierra": "Heroi de la Terra",
    "INVASIÓN": "INVASIÓ",
    "Idioma": "Idioma",
    "Implantes estables. Recuerda: MAYÚS o clic derecho para esquivar rodando.": "Implants estables. Recorda: MAJÚS o clic dret per esquivar rodolant.",
    "Imán": "Imant",
    "Infierno": "Infern",
    "Infiltración: hay que avanzar sin hacer ruido.": "Infiltració: cal avançar sense fer soroll.",
    "JEFE DE OLEADA": "CAP D'ONADA",
    "Juego Militar: Invasión Alienígena": "Joc Militar: Invasió Alienígena",
    "Juego creado por": "Joc creat per",
    "Jugar": "Jugar",
    "LA CIMA": "EL CIM",
    "LA INVASIÓN": "LA INVASIÓ",
    "LA SEÑAL": "EL SENYAL",
    "LA TIERRA": "LA TERRA",
    "La Fortaleza Xylothian se alza sobre las montañas: murallas de energía, reflectores y legiones de élite. Desde aquí se dirige toda la invasión del continente.": "La Fortalesa Xylothian s'alça sobre les muntanyes: muralles d'energia, reflectors i legions d'elit. Des d'aquí es dirigeix tota la invasió del continent.",
    "La Nave Nodriza": "La Nau Nodrissa",
    "La Nave Nodriza se parte en dos. Doce kilómetros de metal vivo arden sobre la Tierra.": "La Nau Nodrissa es parteix en dos. Dotze quilòmetres de metall viu cremen sobre la Terra.",
    "La alarma ha corrido entre los aliens. Bajo la lluvia, los drones refuerzan las ruinas y sus lugartenientes dirigen la búsqueda. Elimínalos antes de que localicen el búnker.": "L'alarma ha corregut entre els aliens. Sota la pluja, els drons reforcen les ruïnes i els seus lloctinents dirigeixen la recerca. Elimina'ls abans que localitzin el búnquer.",
    "La dificultad se aplica al empezar el siguiente escenario.": "La dificultat s'aplica en començar el següent escenari.",
    "La humanidad puede reconstruirse... y, esta vez, mirar las estrellas sin miedo.": "La humanitat pot reconstruir-se... i, aquesta vegada, mirar les estrelles sense por.",
    "La lanzadera atraca en el casco exterior de la Nave Nodriza. Alrededor flotan los restos de los satélites que derribaron en 2139. Abre camino hacia los hangares.": "La llançadora s'acobla al casc exterior de la Nau Nodrissa. Al voltant suren les restes dels satèl·lits que van abatre el 2139. Obre't pas cap als hangars.",
    "La lluvia no los frena. Y los edificios se caen a trozos: mira al suelo.": "La pluja no els atura. I els edificis cauen a trossos: mira a terra.",
    "La mente de un millón de mundos": "La ment d'un milió de mons",
    "La potencia decide dónde puedes usar cada arma.": "La potència decideix on pots fer servir cada arma.",
    "La selva está viva... y ese líquido verde es ácido. No pises los charcos.": "La selva és viva... i aquest líquid verd és àcid. No trepitgis els bassals.",
    "La tecnología viva": "La tecnologia viva",
    "La voz del enemigo en la Tierra": "La veu de l'enemic a la Terra",
    "Las murallas. Sus morteros te tienen localizado: atento a las marcas.": "Les muralles. Els seus morters t'han localitzat: atent a les marques.",
    "Leyenda de Xylos": "Llegenda de Xylos",
    "Ligera y fiable.": "Lleugera i fiable.",
    "Los Xylothians": "Els Xylothians",
    "Los escudos solo paran lo que les llega de frente: rodéalos.": "Els escuts només aturen el que els arriba de cara: envolta'ls.",
    "Los hangares de la Nave Nodriza están llenos de cazadores, drones que atacan en picado. Los ingenieros cargan un rayo capaz de arrasar ciudades enteras. Hay que detenerlos.": "Els hangars de la Nau Nodrissa són plens de caçadors, drons que ataquen en picat. Els enginyers carreguen un raig capaç d'arrasar ciutats senceres. Cal aturar-los.",
    "M: sonido ON": "M: so ON",
    "MAESTRO DE LA SELVA": "MESTRE DE LA SELVA",
    "MAYÚS / clic derecho": "MAJÚS / clic dret",
    "Mejoras": "Millores",
    "Menú": "Menú",
    "Mil años. Un millón de voces. Y tú quieres callarlas todas.": "Mil anys. Un milió de veus. I tu les vols fer callar totes.",
    "Minigun": "Minigun",
    "Minigun: demasiado potente para este escenario": "Minigun: massa potent per a aquest escenari",
    "Modo": "Mode",
    "Monedas y XP a la mitad · todas tus armas permitidas": "Monedes i XP a la meitat · totes les teves armes permeses",
    "Moverse": "Moure's",
    "Munición infinita. Arma pesada.": "Munició infinita. Arma pesant.",
    "Más contactos. Esto se pone feo.": "Més contactes. Això es posa lleig.",
    "Más velocidad e invulnerabilidad": "Més velocitat i invulnerabilitat",
    "Máximo": "Màxim",
    "Música": "Música",
    "Música y efectos": "Música i efectes",
    "NAVE NODRIZA XYLOTHIAN": "NAU NODRISSA XYLOTHIAN",
    "Nacho y Abel": "Nacho i Abel",
    "Nadie pasa a la cámara del Núcleo": "Ningú passa a la cambra del Nucli",
    "Nave-ciudad de doce kilómetros que hace de puente entre el Núcleo y sus colonias. Sin ella, los Xylothians de la Tierra no podían recibir órdenes: por eso el Comandante Supremo la llamó cuando se vio perdido.": "Nau-ciutat de dotze quilòmetres que fa de pont entre el Nucli i les seves colònies. Sense ella, els Xylothians de la Terra no podien rebre ordres: per això el Comandant Suprem la va cridar quan es va veure perdut.",
    "Nexus": "Nexus",
    "Nexus corre hasta la rampa de la fortaleza, roba la lanzadera alienígena y despega tras ella.": "Nexus corre fins a la rampa de la fortalesa, roba la llançadora alienígena i s'enlaira darrere seu.",
    "Nexus sale del búnker a una ciudad que ya no reconoce. Los drones Xylothian patrullan las ruinas buscando supervivientes. Primera misión: destruir el puesto de vigilancia del barrio norte.": "Nexus surt del búnquer a una ciutat que ja no reconeix. Els drons Xylothian patrullen les ruïnes buscant supervivents. Primera missió: destruir el lloc de vigilància del barri nord.",
    "Nexus vuelve a casa. Los supervivientes salen de los búnkeres para ver el amanecer.": "Nexus torna a casa. Els supervivents surten dels búnquers per veure l'alba.",
    "Nexus, aquí el comandante Reyes, desde el búnker. Si me oyes, estás vivo.": "Nexus, aquí el comandant Reyes, des del búnquer. Si em sents, és que ets viu.",
    "Nivel máximo · {x} XP": "Nivell màxim · {x} XP",
    "Nivel {n}": "Nivell {n}",
    "Nivel {n}/{t} · {x}/{m} XP": "Nivell {n}/{t} · {x}/{m} XP",
    "Nocturno": "Nocturn",
    "Normal": "Normal",
    "NÚCLEO DE XYLOS": "NUCLI DE XYLOS",
    "Nítido": "Nítid",
    "OLEADA {o}": "ONADA {o}",
    "OPCIONES": "OPCIONS",
    "Ocho años de guerra. Las capitales caen una tras otra y los supervivientes se esconden bajo los escombros.": "Vuit anys de guerra. Les capitals cauen una darrere l'altra i els supervivents s'amaguen sota la runa.",
    "Oleada {o} de {n}": "Onada {o} de {n}",
    "Oleadas": "Onades",
    "Oleadas sin fin. Cada cinco, un jefe. ¿Cuánto aguantarás?": "Onades sense fi. Cada cinc, un cap. Quant aguantaràs?",
    "Opciones": "Opcions",
    "P / ESC": "P / ESC",
    "PAUSA": "PAUSA",
    "PROYECTO NEXUS": "PROJECTE NEXUS",
    "PUNTOS: {p}": "PUNTS: {p}",
    "Pantalla": "Pantalla",
    "Pantalla completa (F11)": "Pantalla completa (F11)",
    "Pantalla completa (volumen y vídeo en Opciones)": "Pantalla completa (volum i vídeo a Opcions)",
    "Pausa": "Pausa",
    "Pequeño humano. Esta nave ha devorado cien mundos.": "Petit humà. Aquesta nau ha devorat cent mons.",
    "Permite hacer un doble salto en el aire": "Permet fer un doble salt a l'aire",
    "Pistola": "Pistola",
    "Plasma azul": "Plasma blau",
    "Por fin llegas, Nexus. Bienvenido a casa.": "Per fi arribes, Nexus. Benvingut a casa.",
    "Potencia": "Potència",
    "Potencia máxima 4/5 · Armas: Pistola, Escopeta, Fusil, Minigun": "Potència màxima 4/5 · Armes: Pistola, Escopeta, Fusell, Minigun",
    "Potencia máxima {p}/5 · Armas: {l}": "Potència màxima {p}/5 · Armes: {l}",
    "Producción": "Producció",
    "Programación": "Programació",
    "Progreso borrado": "Progrés esborrat",
    "Propulsores": "Propulsors",
    "Proyecto NEXUS": "Projecte NEXUS",
    "Pues que la Tierra sea el último.": "Doncs que la Terra sigui l'últim.",
    "Puntos": "Punts",
    "Puntos: {p}": "Punts: {p}",
    "R / ENTER: reintentar  ·  ESC: menú": "R / ENTER: reintentar  ·  ESC: menú",
    "Recluta": "Recluta",
    "Reflejos": "Reflexos",
    "Reiniciar": "Reiniciar",
    "Reintentar": "Reintentar",
    "Resolución actual: {w}x{h} ({d})": "Resolució actual: {w}x{h} ({d})",
    "Reyes, ¿me oye? ... Nada. Estoy solo.": "Reyes, em sent? ... Res. Estic sol.",
    "Ruinas": "Ruïnes",
    "Ruinas Urbanas": "Ruïnes Urbanes",
    "Ruinas inestables: las armas pesadas derrumbarían los edificios.": "Ruïnes inestables: les armes pesants farien caure els edificis.",
    "RÉCORDS": "RÈCORDS",
    "S / abajo": "S / avall",
    "SECTOR": "SECTOR",
    "SECTOR {s} · OLEADA {o}/{n}": "SECTOR {s} · ONADA {o}/{n}",
    "SELECCIONA NIVEL": "SELECCIONA NIVELL",
    "SUPERVIVENCIA": "SUPERVIVÈNCIA",
    "SUPERVIVENCIA · OLEADA {o}": "SUPERVIVÈNCIA · ONADA {o}",
    "Salir": "Sortir",
    "Saltar (doble salto con Propulsores)": "Saltar (doble salt amb Propulsors)",
    "Se consigue en el nivel {n} del Battle Pass": "S'aconsegueix al nivell {n} del Battle Pass",
    "Seis perdigones. Devastadora de cerca.": "Sis perdigons. Devastadora de prop.",
    "Selva": "Selva",
    "Selva Tecnológica": "Selva Tecnològica",
    "Semi": "Semi",
    "Señor de las ruinas": "Senyor de les ruïnes",
    "Sin recibir daño": "Sense rebre dany",
    "Suave": "Suau",
    "Supervivencia": "Supervivència",
    "TIENDA": "BOTIGA",
    "Te han detectado. Llegan refuerzos.": "T'han detectat. Arriben reforços.",
    "Te recibo con interferencias. Estás fuera de la atmósfera, Nexus.": "Et rebo amb interferències. Ets fora de l'atmosfera, Nexus.",
    "Tienda": "Botiga",
    "Tipografías": "Tipografies",
    "Todavía no hay récords.": "Encara no hi ha rècords.",
    "TÍTULO": "TÍTOL",
    "Título: {t}": "Títol: {t}",
    "Tóxico": "Tòxic",
    "UNIFORME": "UNIFORME",
    "Un General Xylothian ha levantado una base sobre el antiguo centro de la ciudad. Desde allí controla todo el sector. Derríbalo y el camino hacia el sur quedará abierto.": "Un General Xylothian ha aixecat una base sobre l'antic centre de la ciutat. Des d'allà controla tot el sector. Abat-lo i el camí cap al sud quedarà obert.",
    "Una conciencia nacida hace miles de años que ha absorbido cientos de civilizaciones. Cada mundo conquistado le añadía millones de voces. La Tierra iba a ser la siguiente. Ahora solo queda el silencio.": "Una consciència nascuda fa milers d'anys que ha absorbit centenars de civilitzacions. Cada món conquerit li afegia milions de veus. La Terra havia de ser la següent. Ara només queda el silenci.",
    "Una mente fundida con el metal": "Una ment fosa amb el metall",
    "Uniforme {u}": "Uniforme {u}",
    "Ventana": "Finestra",
    "Ver escena": "Veure escena",
    "Ver introducción": "Veure introducció",
    "Verde = completado · Cuadros = potencia · Estrellas: completar, sin daño, rápido": "Verd = completat · Quadres = potència · Estrelles: completar, sense dany, ràpid",
    "Veterano": "Veterà",
    "Voltereta: esquiva sin recibir daño": "Tombarella: esquiva sense rebre dany",
    "Volver al menú": "Tornar al menú",
    "Vuelve a hacer clic para confirmar": "Torna a fer clic per confirmar",
    "XYLOS": "XYLOS",
    "Xylos": "Xylos",
    "Xylos, el Mundo Colmena": "Xylos, el Món Rusc",
    "YouTube, libre de derechos": "YouTube, lliure de drets",
    "escala x{n}, píxel perfecto": "escala x{n}, píxel perfecte",
    "píxeles nítidos": "píxels nítids",
    "suavizado": "suavitzat",
    "todas": "totes",
    "{a}: demasiado potente para este escenario": "{a}: massa potent per a aquest escenari",
    "¡A luchar!": "A lluitar!",
    "¡Casi lo tienes!": "Gairebé ho tens!",
    "¡Cuidado con los bichos brillantes! Explotan si se te acercan.": "Compte amb els bitxos brillants! Exploten si se t'acosten.",
    "¡El Comandante de Élite viene a por ti!": "El Comandant d'Elit ve a per tu!",
    "¡Está perdiendo energía! Sigue así, Nexus.": "Està perdent energia! Continua així, Nexus.",
    "¡Flota, a mí! ¡Destruidlo!": "Flota, a mi! Destruïu-lo!",
    "¡Gracias por jugar!": "Gràcies per jugar!",
    "¡Imposible! ¡La señal no te alcanza!": "Impossible! El senyal no t'arriba!",
    "¡La selva se marchita! Está perdiendo fuerza.": "La selva es marceix! Està perdent força.",
    "¡NUEVO RÉCORD!": "NOU RÈCORD!",
    "¡Nexus! Te oigo... la señal vuelve. ¡Acaba con él!": "Nexus! Et sento... el senyal torna. Acaba amb ell!",
    "¡REFUERZOS!": "REFORÇOS!",
    "¡SECTOR LIMPIO!": "SECTOR NET!",
    "¡SIN BALAS! Recoge munición o cambia de arma (Q)": "SENSE BALES! Recull munició o canvia d'arma (Q)",
    "¡Soldados de a pie! Esos caminan y disparan en línea recta. ¡Salta!": "Soldats a peu! Aquests caminen i disparen en línia recta. Salta!",
    "¡Te faltan {n} monedas!": "Et falten {n} monedes!",
    "¡Toda la Tierra está contigo, soldado!": "Tota la Terra és amb tu, soldat!",
    "¡{a} desbloqueada!": "{a} desbloquejada!",
    "¡{m} nivel {n} desbloqueado!": "{m} nivell {n} desbloquejat!",
    "· JUEGO MILITAR ·": "· JOC MILITAR ·",
    "Ártico": "Àrtic",
    "Élite roja": "Elit roja",
    "ÓRBITA": "ÒRBITA",
    "Órbita": "Òrbita",
    "Órbita: la Nave Nodriza": "Òrbita: la Nau Nodrissa",
    "Última iniciativa del Ejército Unificado, creada por la doctora Vega bajo el mando del comandante Reyes. Un soldado voluntario con implantes que lo hacen inmune a la señal mental Xylothian. Era el único que podía acercarse a sus líderes sin ser dominado. Nadie esperaba que volviera.": "Última iniciativa de l'Exèrcit Unificat, creada per la doctora Vega sota el comandament del comandant Reyes. Un soldat voluntari amb implants que el fan immune al senyal mental Xylothian. Era l'únic que podia acostar-se als seus líders sense ser dominat. Ningú no esperava que tornés.",
}


EN = {
    "LOGROS": "ACHIEVEMENTS",
    "LOGRO DESBLOQUEADO": "ACHIEVEMENT UNLOCKED",
    "Logro secreto": "Secret achievement",
    "Placa {n}/{t}": "Tag {n}/{t}",
    "Saltar  >>": "Skip  >>",
    "Bronce 50 · Plata 150 · Oro 400 · Platino 1000 monedas": "Bronze 50 · Silver 150 · Gold 400 · Platinum 1000 coins",
    "Bronce": "Bronze",
    "Plata": "Silver",
    "Oro": "Gold",
    "Platino": "Platinum",
    "Primer contacto": "First contact",
    "Completa el escenario 1-1.": "Complete stage 1-1.",
    "Las ruinas son nuestras": "The ruins are ours",
    "Derrota al General Xylothian.": "Defeat the Xylothian General.",
    "Poda radical": "Radical pruning",
    "Derrota al Maestro de la Selva.": "Defeat the Jungle Master.",
    "Sin voz": "Voiceless",
    "Derrota al Comandante Supremo.": "Defeat the Supreme Commander.",
    "Fuera de órbita": "Out of orbit",
    "Destruye la Nave Nodriza.": "Destroy the Mothership.",
    "Silencio": "Silence",
    "Apaga el Núcleo de Xylos y termina la historia.": "Shut down the Xylos Core and finish the story.",
    "Hasta el final": "Until the end",
    "Mira la cinemática final entera sin saltarla.": "Watch the whole ending without skipping it.",
    "Intocable": "Untouchable",
    "Derrota a un jefe sin recibir ni un golpe.": "Defeat a boss without taking a single hit.",
    "Contrarreloj": "Time attack",
    "Consigue la estrella de rapidez en 5 escenarios.": "Get the speed star in 5 stages.",
    "Constelación": "Constellation",
    "Consigue las 45 estrellas.": "Get all 45 stars.",
    "Veterano de verdad": "True veteran",
    "Derrota al Núcleo de Xylos en Difícil.": "Defeat the Xylos Core on Hard.",
    "Superviviente": "Survivor",
    "Llega a la oleada 10 en Supervivencia.": "Reach wave 10 in Survival.",
    "Leyenda de la arena": "Arena legend",
    "Llega a la oleada 20 en Supervivencia.": "Reach wave 20 in Survival.",
    "Exterminador": "Exterminator",
    "Elimina a 500 alienígenas.": "Kill 500 aliens.",
    "Acróbata": "Acrobat",
    "Haz 100 volteretas.": "Do 100 dodge rolls.",
    "Por la espalda": "From behind",
    "Elimina a un escudero disparándole por detrás.": "Kill a shield bearer by shooting it from behind.",
    "Carambola": "Chain reaction",
    "Haz que la explosión de un kamikaze elimine a otro alienígena.": "Make a kamikaze's explosion kill another alien.",
    "Arsenal completo": "Full arsenal",
    "Consigue las cinco armas.": "Get all five weapons.",
    "Al máximo": "Maxed out",
    "Sube todas las mejoras al máximo.": "Max out every upgrade.",
    "Todo de oro": "All gold",
    "Equípate el uniforme y el aspecto de arma dorados.": "Equip the golden uniform and weapon skin.",
    "Placa encontrada": "Tag found",
    "Encuentra una placa de identificación escondida.": "Find a hidden dog tag.",
    "Hay cosas brillando donde nadie mira.": "Things glint where nobody looks.",
    "Nadie se queda atrás": "Nobody left behind",
    "Recupera las cinco placas de identificación escondidas.": "Recover the five hidden dog tags.",
    "Los soldados caídos dejaron algo en cada sector.": "Fallen soldiers left something in every sector.",
    "Ojo por ojo": "An eye for an eye",
    "Revienta el ojo de la torre de vigilancia del escenario 1-1.": "Burst the eye of the watchtower in stage 1-1.",
    "Alguien te vigila desde el fondo del primer escenario.": "Someone watches you from the back of the first stage.",
    "Avistamiento": "Sighting",
    "Derriba uno de los ovnis que cruzan el cielo del fondo.": "Shoot down one of the UFOs crossing the sky in the background.",
    "Mira al cielo.": "Look at the sky.",
    "Vieja escuela": "Old school",
    "Derrota al Núcleo de Xylos usando solo la pistola.": "Defeat the Xylos Core using only the pistol.",
    "A veces, menos es más.": "Sometimes less is more.",
    "Código secreto": "Secret code",
    "Introduce el código más famoso de los videojuegos en el menú.": "Enter the most famous code in video games on the menu.",
    "Arriba, arriba...": "Up, up...",
    "Mal cálculo": "Miscalculation",
    "Muere por la explosión de un kamikaze.": "Die from a kamikaze's explosion.",
    "No los abraces.": "Don't hug them.",
    "Héroe de la galaxia": "Hero of the galaxy",
    "Consigue todos los demás logros.": "Unlock every other achievement.",
    "Armas": "Weapons",
    "Aspecto": "Looks",
    "+20 VIDA": "+20 HP",
    "{n} monedas": "{n} coins",
    "+10 vida · ¡prepárate!": "+10 HP · get ready!",
    "+15% de daño con todas las armas": "+15% damage with all weapons",
    "+20 de vida máxima por nivel": "+20 max HP per level",
    "+30% de munición máxima": "+30% max ammo",
    "+{m} monedas · +{x} XP": "+{m} coins · +{x} XP",
    "1-5 / Q / rueda": "1-5 / Q / wheel",
    "< Menú": "< Menu",
    "< Volver": "< Back",
    "A / D  o  flechas": "A / D  or  arrows",
    "ALIENÍGENA": "INVASION",
    "ARENA": "ARENA",
    "ARMA": "WEAPON",
    "Activar / silenciar el sonido": "Toggle sound on / off",
    "Ahí está el General. Derríbalo y el sector norte será nuestro.": "There's the General. Take him down and the northern sector is ours.",
    "Al otro lado del portal, un planeta de cielo violeta. Los restos de la Nave Nodriza revelaron la verdad: todos los Xylothians obedecen a una sola mente, el Núcleo de Xylos. Y está aquí.": "Beyond the portal lies a planet with a violet sky. The Mothership's wreckage revealed the truth: every Xylothian obeys a single mind, the Xylos Core. And it's here.",
    "Al sur, donde había bosques, ahora crece la Selva Tecnológica: plantas y máquinas fusionadas. Los Xylothians no construyen, cultivan. Y están cultivando la Tierra.": "To the south, where forests once stood, the Techno-Jungle now grows: plants and machines fused together. The Xylothians don't build, they grow. And they're growing Earth.",
    "Algunas mejoras se abren al avanzar en la historia.": "Some upgrades unlock as you progress through the story.",
    "Aquí tus armas no sirven. Aquí solo existo yo.": "Your weapons are useless here. Here, only I exist.",
    "Arcoíris": "Rainbow",
    "Arena": "Arena",
    "Arma bloqueada aquí: {a} · Equipada: {b}": "Weapon locked here: {a} · Equipped: {b}",
    "Arte nuevo e intro": "New art and intro",
    "Aspecto de arma {a}": "Weapon skin {a}",
    "Atrae los objetos desde más lejos": "Pulls in items from farther away",
    "Atraviesa a los enemigos. Tecnología Xylothian.": "Pierces through enemies. Xylothian technology.",
    "Atraviesa a los enemigos. Tecnología Xylothian. Disponible al completar 4-2.": "Pierces through enemies. Xylothian technology. Unlocks after completing 4-2.",
    "Auto": "Auto",
    "Automático y preciso.": "Automatic and precise.",
    "AÑO 2139": "YEAR 2139",
    "AÑO 2147": "YEAR 2147",
    "Año 2139. Una noche, el cielo de la Tierra se abre: decenas de portales de luz violeta aparecen sobre las ciudades.": "2139. One night, Earth's sky tears open: dozens of violet portals of light appear above the cities.",
    "Año 2147. Nexus despierta en un búnker bajo la ciudad. La humanidad ya no tiene a nadie más. Su misión: llegar hasta el corazón de la invasión.": "2147. Nexus wakes up in a bunker beneath the city. Humanity has no one else left. His mission: reach the heart of the invasion.",
    "BALAS: {b}/{m}": "AMMO: {b}/{m}",
    "BALAS: ∞": "AMMO: ∞",
    "BATTLE PASS": "BATTLE PASS",
    "Bajar de una plataforma": "Drop through a platform",
    "Balas": "Ammo",
    "Battle Pass": "Battle Pass",
    "Battle Pass nivel {n}": "Battle Pass level {n}",
    "Blindaje": "Armor",
    "Bloqueado": "Locked",
    "Borrar progreso": "Erase progress",
    "COMANDANTE DE ÉLITE": "ELITE COMMANDER",
    "COMANDANTE SUPREMO": "SUPREME COMMANDER",
    "CRÉDITOS": "CREDITS",
    "Cada escenario limita la potencia de las armas que puedes usar.": "Each stage limits the power of the weapons you can use.",
    "Cambiar de arma": "Switch weapon",
    "Campo supresor de la colmena: las armas pesadas no funcionan.": "Hive suppression field: heavy weapons don't work.",
    "Cargadores": "Magazines",
    "Català": "Català",
    "Cazador de aliens": "Alien Hunter",
    "Cañón de plasma": "Plasma cannon",
    "Cibernético": "Cyber",
    "Clic / ESPACIO para continuar": "Click / SPACE to continue",
    "Clic / ESPACIO para ver todo el texto": "Click / SPACE to show all text",
    "Clic izquierdo": "Left click",
    "Clásico": "Classic",
    "Cmdte. Reyes": "Cmdr. Reyes",
    "Completa": "Full",
    "Completa el sector {n} para leerlo.": "Complete sector {n} to read it.",
    "Completa {e}": "Complete {e}",
    "Completado": "Completed",
    "Comprar {c}": "Buy {c}",
    "Consigue más subiendo de nivel en el Battle Pass.": "Earn more by leveling up the Battle Pass.",
    "Continuar": "Continue",
    "Créditos": "Credits",
    "Cuando un enemigo brilla, va a atacar: ¡apártate o rueda!": "When an enemy glows, it's about to attack: move or roll!",
    "DESPEGUE": "LIFTOFF",
    "Daño": "Damage",
    "De ellos salen los Xylothians, una especie que no piensa: obedece. Todos sus soldados son extensiones de una sola mente.": "Out of them pour the Xylothians, a species that doesn't think: it obeys. Every one of their soldiers is an extension of a single mind.",
    "Desierto": "Desert",
    "Detente. Únete a nosotros. Deja de luchar.": "Stop. Join us. Stop fighting.",
    "Dibujado con código (tools/)": "Drawn with code (tools/)",
    "Dificultad": "Difficulty",
    "Dificultad: Normal (se cambia en Opciones)": "Difficulty: Normal (change it in Options)",
    "Dificultad: {d} (se cambia en Opciones)": "Difficulty: {d} (change it in Options)",
    "Difícil": "Hard",
    "Diseño de juego": "Game design",
    "Disp/s": "Shots/s",
    "Disparar (mantén: armas automáticas)": "Shoot (hold: automatic weapons)",
    "Disponible al completar {e}.": "Unlocks after completing {e}.",
    "Dorado": "Golden",
    "Dra. Vega": "Dr. Vega",
    "EL PORTAL": "THE PORTAL",
    "EL REGRESO": "THE RETURN",
    "ENEMIGOS: {n}": "ENEMIES: {n}",
    "ESPACIO / W / arriba": "SPACE / W / up",
    "ESPACIO / clic: saltar": "SPACE / click: skip",
    "ESPACIO / clic: siguiente  ·  ESC: saltar": "SPACE / click: next  ·  ESC: skip",
    "Efectos": "Effects",
    "El Comandante Supremo se desploma sobre la nieve. Con su último aliento, lanza una señal hacia el cielo.": "The Supreme Commander collapses onto the snow. With his last breath, he sends a signal into the sky.",
    "El Guardián. Es lo último que hay entre el Núcleo y yo.": "The Guardian. The last thing standing between the Core and me.",
    "El Maestro de la Selva, el bio-constructor que hace crecer esta jungla, protege su corazón. Si cae, la selva dejará de avanzar y la fortaleza quedará al descubierto.": "The Jungle Master, the bio-builder who makes this jungle grow, guards its heart. If he falls, the jungle will stop spreading and the fortress will be exposed.",
    "El Maestro de la Selva. Y esa plataforma podrida no aguantará mucho.": "The Jungle Master. And that rotten platform won't hold for long.",
    "El Núcleo de Xylos": "The Xylos Core",
    "El Núcleo de Xylos abre su ojo inmenso. Miles de años de conquistas, cientos de mundos absorbidos. Hoy, por primera vez, alguien ha llegado hasta aquí. Acaba con esto, Nexus.": "The Xylos Core opens its immense eye. Thousands of years of conquest, hundreds of worlds absorbed. Today, for the first time, someone has made it this far. End this, Nexus.",
    "El Núcleo de Xylos se apaga. Por primera vez en mil años, la colmena queda en silencio.": "The Xylos Core goes dark. For the first time in a thousand years, the hive falls silent.",
    "El que hace crecer la jungla": "The one who grows the jungle",
    "El suelo del hangar está cargado. Salta en cuanto veas chispas.": "The hangar floor is charged. Jump as soon as you see sparks.",
    "El suelo se rompe bajo tus pies. Como tu especie.": "The ground breaks beneath your feet. Just like your species.",
    "En el corazón de la colmena, un campo supresor bloquea las armas pesadas. El Guardián de la Colmena vigila la entrada a la cámara del Núcleo. Solo tus reflejos te llevarán más allá.": "At the heart of the hive, a suppression field blocks heavy weapons. The Hive Guardian watches the entrance to the Core chamber. Only your reflexes will get you past it.",
    "En el puente de mando te espera la Nave Nodriza en persona: una conciencia viva fundida con el metal. Si cae, la flota se quedará sin órdenes y el portal hacia su mundo quedará abierto.": "On the bridge, the Mothership herself awaits: a living mind fused with metal. If she falls, the fleet will be left without orders and the portal to their world will stay open.",
    "En la Tierra, los portales se cierran uno a uno. Sin su mente, los Xylothians dejan de luchar.": "On Earth, the portals close one by one. Without their mind, the Xylothians stop fighting.",
    "En la cima de la fortaleza espera el Comandante Supremo, la voz del enemigo en la Tierra. Si cae, los Xylothians quedarán sin líder... o eso cree Nexus.": "At the top of the fortress waits the Supreme Commander, the enemy's voice on Earth. If he falls, the Xylothians will be leaderless... or so Nexus believes.",
    "En medio de la selva se esconde un laboratorio alienígena lleno de criaturas en tanques. El aire está cargado de gas inflamable: cuidado con lo que disparas.": "Deep in the jungle hides an alien lab full of creatures in tanks. The air is thick with flammable gas: watch what you shoot.",
    "En menos de {s} s": "In under {s} s",
    "English": "English",
    "Entre los restos se abre un portal: el camino a Xylos, su mundo de origen. Nexus no se lo piensa dos veces.": "Among the wreckage a portal opens: the way to Xylos, their homeworld. Nexus doesn't think twice.",
    "Equipa los aspectos en Tienda > Aspecto.": "Equip skins in Shop > Looks.",
    "Equipada": "Equipped",
    "Equipar": "Equip",
    "Es él, Nexus: la voz de la mente en la Tierra.": "That's him, Nexus: the voice of the mind on Earth.",
    "Esas plataformas son chatarra que flota. Calcula bien los saltos.": "Those platforms are floating scrap. Time your jumps well.",
    "Escalado": "Scaling",
    "Escopeta": "Shotgun",
    "Escudos de energía: por delante no les haces nada. ¡Rodéalos!": "Energy shields: you can't hurt them from the front. Flank them!",
    "Esos tanques... están criando soldados. Y las tuberías sueltan gas tóxico.": "Those tanks... they're breeding soldiers. And the pipes are leaking toxic gas.",
    "Español": "Español",
    "Especie colectiva originaria del planeta Xylos. Ningún individuo piensa por sí mismo: todos son extensiones de una sola mente. Llegaron a la Tierra en 2139 a través de portales y en ocho años hicieron caer todas las capitales.": "A collective species from the planet Xylos. No individual thinks for itself: all are extensions of a single mind. They reached Earth in 2139 through portals, and in eight years every capital had fallen.",
    "Estoy dentro. El suelo del patio está electrificado a trozos.": "I'm in. The courtyard floor is electrified in patches.",
    "Estrellas: completa el escenario, sin recibir daño y a tiempo.": "Stars: clear the stage, take no damage and beat the clock.",
    "Estrellas: {e}/3 · récord de tiempo: {s} s": "Stars: {e}/3 · best time: {s} s",
    "Están cargando el rayo. ¡No hay tiempo!": "They're charging the beam. There's no time!",
    "Estándar": "Standard",
    "Expediente bloqueado": "File locked",
    "F11: pantalla completa  ·  M: silenciar": "F11: fullscreen  ·  M: mute",
    "FIN": "END",
    "FIN DE LA PARTIDA": "GAME OVER",
    "Fortaleza": "Fortress",
    "Fortaleza Xylothian": "Xylothian Fortress",
    "Fusil": "Rifle",
    "Fácil": "Easy",
    "GENERAL XYLOTHIAN": "XYLOTHIAN GENERAL",
    "GUARDIÁN DE LA COLMENA": "HIVE GUARDIAN",
    "GUÍA": "GUIDE",
    "Gas inflamable en el laboratorio: nada más potente que la escopeta.": "Flammable gas in the lab: nothing stronger than the shotgun.",
    "Gráficos originales": "Original graphics",
    "Guardián del patio interior": "Inner courtyard guardian",
    "Guía": "Guide",
    "HAS CAÍDO": "YOU FELL",
    "HECHO POR NACHO Y ABEL": "MADE BY NACHO AND ABEL",
    "HISTORIA": "STORY",
    "Han soltado tropas en el casco.": "They've dropped troops on the hull.",
    "Has caído en combate. Los Xylothians avanzan. ¿Qué harás, Nexus?": "You fell in combat. The Xylothians advance. What will you do, Nexus?",
    "Has entrado por las cloacas. Para cruzar el patio interior tendrás que moverte en silencio y eliminar al Comandante de Élite que vigila la segunda línea.": "You got in through the sewers. To cross the inner courtyard you'll have to move quietly and take out the Elite Commander guarding the second line.",
    "Has superado {o} oleadas y eliminado a {b} enemigos.": "You survived {o} waves and took out {b} enemies.",
    "Haz clic para empezar": "Click to start",
    "Historia": "Story",
    "Historia desbloqueada: El Núcleo de Xylos": "Story unlocked: The Xylos Core",
    "Historia desbloqueada: La Nave Nodriza": "Story unlocked: The Mothership",
    "Historia desbloqueada: La tecnología viva": "Story unlocked: Living technology",
    "Historia desbloqueada: Los Xylothians": "Story unlocked: The Xylothians",
    "Historia desbloqueada: Proyecto NEXUS": "Story unlocked: Project NEXUS",
    "Historia desbloqueada: {h}": "Story unlocked: {h}",
    "Humano... ¿Por qué no te arrodillas como los demás?": "Human... why don't you kneel like the others?",
    "Héroe de la Tierra": "Hero of Earth",
    "INVASIÓN": "ALIEN",
    "Idioma": "Language",
    "Implantes estables. Recuerda: MAYÚS o clic derecho para esquivar rodando.": "Implants stable. Remember: SHIFT or right click to dodge-roll.",
    "Imán": "Magnet",
    "Infierno": "Inferno",
    "Infiltración: hay que avanzar sin hacer ruido.": "Infiltration: you have to move without a sound.",
    "JEFE DE OLEADA": "WAVE BOSS",
    "Juego Militar: Invasión Alienígena": "Military Game: Alien Invasion",
    "Juego creado por": "Game created by",
    "Jugar": "Play",
    "LA CIMA": "SUMMIT",
    "LA INVASIÓN": "THE INVASION",
    "LA SEÑAL": "THE SIGNAL",
    "LA TIERRA": "EARTH",
    "La Fortaleza Xylothian se alza sobre las montañas: murallas de energía, reflectores y legiones de élite. Desde aquí se dirige toda la invasión del continente.": "The Xylothian Fortress towers over the mountains: energy walls, searchlights and elite legions. The whole invasion of the continent is run from here.",
    "La Nave Nodriza": "The Mothership",
    "La Nave Nodriza se parte en dos. Doce kilómetros de metal vivo arden sobre la Tierra.": "The Mothership splits in two. Twelve kilometers of living metal burn above the Earth.",
    "La alarma ha corrido entre los aliens. Bajo la lluvia, los drones refuerzan las ruinas y sus lugartenientes dirigen la búsqueda. Elimínalos antes de que localicen el búnker.": "The alarm has spread among the aliens. In the rain, drones reinforce the ruins and their lieutenants lead the search. Take them out before they find the bunker.",
    "La dificultad se aplica al empezar el siguiente escenario.": "Difficulty applies when the next stage starts.",
    "La humanidad puede reconstruirse... y, esta vez, mirar las estrellas sin miedo.": "Humanity can rebuild... and, this time, look at the stars without fear.",
    "La lanzadera atraca en el casco exterior de la Nave Nodriza. Alrededor flotan los restos de los satélites que derribaron en 2139. Abre camino hacia los hangares.": "The shuttle docks on the Mothership's outer hull. Around it float the remains of the satellites they shot down in 2139. Fight your way to the hangars.",
    "La lluvia no los frena. Y los edificios se caen a trozos: mira al suelo.": "The rain won't stop them. And the buildings are falling apart: watch your step.",
    "La mente de un millón de mundos": "The mind of a million worlds",
    "La potencia decide dónde puedes usar cada arma.": "Power decides where you can use each weapon.",
    "La selva está viva... y ese líquido verde es ácido. No pises los charcos.": "The jungle is alive... and that green liquid is acid. Stay out of the puddles.",
    "La tecnología viva": "Living technology",
    "La voz del enemigo en la Tierra": "The enemy's voice on Earth",
    "Las murallas. Sus morteros te tienen localizado: atento a las marcas.": "The walls. Their mortars have you locked: watch for the markers.",
    "Leyenda de Xylos": "Legend of Xylos",
    "Ligera y fiable.": "Light, reliable.",
    "Los Xylothians": "The Xylothians",
    "Los escudos solo paran lo que les llega de frente: rodéalos.": "Shields only stop what hits them head-on: flank them.",
    "Los hangares de la Nave Nodriza están llenos de cazadores, drones que atacan en picado. Los ingenieros cargan un rayo capaz de arrasar ciudades enteras. Hay que detenerlos.": "The Mothership's hangars are full of hunters, drones that dive-bomb you. The engineers are charging a beam that can wipe out entire cities. They must be stopped.",
    "M: sonido ON": "M: sound ON",
    "MAESTRO DE LA SELVA": "JUNGLE MASTER",
    "MAYÚS / clic derecho": "SHIFT / right click",
    "Mejoras": "Upgrades",
    "Menú": "Menu",
    "Mil años. Un millón de voces. Y tú quieres callarlas todas.": "A thousand years. A million voices. And you want to silence them all.",
    "Minigun": "Minigun",
    "Minigun: demasiado potente para este escenario": "Minigun: too powerful for this stage",
    "Modo": "Mode",
    "Monedas y XP a la mitad · todas tus armas permitidas": "Half coins and XP · all your weapons allowed",
    "Moverse": "Move",
    "Munición infinita. Arma pesada.": "Infinite ammo. Heavy weapon.",
    "Más contactos. Esto se pone feo.": "More contacts. This is getting ugly.",
    "Más velocidad e invulnerabilidad": "More speed and invulnerability",
    "Máximo": "Max",
    "Música": "Music",
    "Música y efectos": "Music and SFX",
    "NAVE NODRIZA XYLOTHIAN": "XYLOTHIAN MOTHERSHIP",
    "Nacho y Abel": "Nacho and Abel",
    "Nadie pasa a la cámara del Núcleo": "No one enters the Core chamber",
    "Nave-ciudad de doce kilómetros que hace de puente entre el Núcleo y sus colonias. Sin ella, los Xylothians de la Tierra no podían recibir órdenes: por eso el Comandante Supremo la llamó cuando se vio perdido.": "A twelve-kilometer city-ship that serves as the bridge between the Core and its colonies. Without it, the Xylothians on Earth couldn't receive orders: that's why the Supreme Commander called it in when all seemed lost.",
    "Nexus": "Nexus",
    "Nexus corre hasta la rampa de la fortaleza, roba la lanzadera alienígena y despega tras ella.": "Nexus races to the fortress ramp, steals the alien shuttle and lifts off after it.",
    "Nexus sale del búnker a una ciudad que ya no reconoce. Los drones Xylothian patrullan las ruinas buscando supervivientes. Primera misión: destruir el puesto de vigilancia del barrio norte.": "Nexus leaves the bunker for a city he no longer recognizes. Xylothian drones patrol the ruins hunting for survivors. First mission: destroy the north district watch post.",
    "Nexus vuelve a casa. Los supervivientes salen de los búnkeres para ver el amanecer.": "Nexus comes home. The survivors emerge from the bunkers to watch the sunrise.",
    "Nexus, aquí el comandante Reyes, desde el búnker. Si me oyes, estás vivo.": "Nexus, this is Commander Reyes, from the bunker. If you can hear me, you're alive.",
    "Nivel máximo · {x} XP": "Max level · {x} XP",
    "Nivel {n}": "Level {n}",
    "Nivel {n}/{t} · {x}/{m} XP": "Level {n}/{t} · {x}/{m} XP",
    "Nocturno": "Night",
    "Normal": "Normal",
    "NÚCLEO DE XYLOS": "XYLOS CORE",
    "Nítido": "Sharp",
    "OLEADA {o}": "WAVE {o}",
    "OPCIONES": "OPTIONS",
    "Ocho años de guerra. Las capitales caen una tras otra y los supervivientes se esconden bajo los escombros.": "Eight years of war. The capitals fall one after another and the survivors hide beneath the rubble.",
    "Oleada {o} de {n}": "Wave {o} of {n}",
    "Oleadas": "Waves",
    "Oleadas sin fin. Cada cinco, un jefe. ¿Cuánto aguantarás?": "Endless waves. A boss every five. How long can you last?",
    "Opciones": "Options",
    "P / ESC": "P / ESC",
    "PAUSA": "PAUSED",
    "PROYECTO NEXUS": "PROJECT NEXUS",
    "PUNTOS: {p}": "SCORE: {p}",
    "Pantalla": "Display",
    "Pantalla completa (F11)": "Fullscreen (F11)",
    "Pantalla completa (volumen y vídeo en Opciones)": "Fullscreen (volume and video in Options)",
    "Pausa": "Pause",
    "Pequeño humano. Esta nave ha devorado cien mundos.": "Puny human. This ship has devoured a hundred worlds.",
    "Permite hacer un doble salto en el aire": "Lets you double jump in midair",
    "Pistola": "Pistol",
    "Plasma azul": "Blue plasma",
    "Por fin llegas, Nexus. Bienvenido a casa.": "At last you arrive, Nexus. Welcome home.",
    "Potencia": "Power",
    "Potencia máxima 4/5 · Armas: Pistola, Escopeta, Fusil, Minigun": "Max power 4/5 · Weapons: Pistol, Shotgun, Rifle, Minigun",
    "Potencia máxima {p}/5 · Armas: {l}": "Max power {p}/5 · Weapons: {l}",
    "Producción": "Production",
    "Programación": "Programming",
    "Progreso borrado": "Progress erased",
    "Propulsores": "Thrusters",
    "Proyecto NEXUS": "Project NEXUS",
    "Pues que la Tierra sea el último.": "Then let Earth be the last.",
    "Puntos": "Score",
    "Puntos: {p}": "Score: {p}",
    "R / ENTER: reintentar  ·  ESC: menú": "R / ENTER: retry  ·  ESC: menu",
    "Recluta": "Recruit",
    "Reflejos": "Reflexes",
    "Reiniciar": "Restart",
    "Reintentar": "Retry",
    "Resolución actual: {w}x{h} ({d})": "Current resolution: {w}x{h} ({d})",
    "Reyes, ¿me oye? ... Nada. Estoy solo.": "Reyes, do you read me? ... Nothing. I'm alone.",
    "Ruinas": "Ruins",
    "Ruinas Urbanas": "Urban Ruins",
    "Ruinas inestables: las armas pesadas derrumbarían los edificios.": "Unstable ruins: heavy weapons would bring the buildings down.",
    "RÉCORDS": "RECORDS",
    "S / abajo": "S / down",
    "SECTOR": "SECTOR",
    "SECTOR {s} · OLEADA {o}/{n}": "SECTOR {s} · WAVE {o}/{n}",
    "SELECCIONA NIVEL": "SELECT LEVEL",
    "SUPERVIVENCIA": "SURVIVAL",
    "SUPERVIVENCIA · OLEADA {o}": "SURVIVAL · WAVE {o}",
    "Salir": "Quit",
    "Saltar (doble salto con Propulsores)": "Jump (double jump with Thrusters)",
    "Se consigue en el nivel {n} del Battle Pass": "Unlocked at Battle Pass level {n}",
    "Seis perdigones. Devastadora de cerca.": "Six pellets. Devastating up close.",
    "Selva": "Jungle",
    "Selva Tecnológica": "Techno-Jungle",
    "Semi": "Semi",
    "Señor de las ruinas": "Lord of the ruins",
    "Sin recibir daño": "No damage taken",
    "Suave": "Smooth",
    "Supervivencia": "Survival",
    "TIENDA": "SHOP",
    "Te han detectado. Llegan refuerzos.": "You've been spotted. Reinforcements incoming.",
    "Te recibo con interferencias. Estás fuera de la atmósfera, Nexus.": "Reading you with interference. You're outside the atmosphere, Nexus.",
    "Tienda": "Shop",
    "Tipografías": "Fonts",
    "Todavía no hay récords.": "No records yet.",
    "TÍTULO": "TITLE",
    "Título: {t}": "Title: {t}",
    "Tóxico": "Toxic",
    "UNIFORME": "UNIFORM",
    "Un General Xylothian ha levantado una base sobre el antiguo centro de la ciudad. Desde allí controla todo el sector. Derríbalo y el camino hacia el sur quedará abierto.": "A Xylothian General has built a base over the old city center. From there he controls the whole sector. Take him down and the road south will be open.",
    "Una conciencia nacida hace miles de años que ha absorbido cientos de civilizaciones. Cada mundo conquistado le añadía millones de voces. La Tierra iba a ser la siguiente. Ahora solo queda el silencio.": "A consciousness born thousands of years ago that has absorbed hundreds of civilizations. Every conquered world added millions of voices to it. Earth was going to be next. Now only silence remains.",
    "Una mente fundida con el metal": "A mind fused with metal",
    "Uniforme {u}": "Uniform {u}",
    "Ventana": "Windowed",
    "Ver escena": "Watch scene",
    "Ver introducción": "Watch intro",
    "Verde = completado · Cuadros = potencia · Estrellas: completar, sin daño, rápido": "Green = completed · Boxes = power · Stars: clear, no damage, fast",
    "Veterano": "Veteran",
    "Voltereta: esquiva sin recibir daño": "Roll: dodge without taking damage",
    "Volver al menú": "Back to menu",
    "Vuelve a hacer clic para confirmar": "Click again to confirm",
    "XYLOS": "XYLOS",
    "Xylos": "Xylos",
    "Xylos, el Mundo Colmena": "Xylos, the Hive World",
    "YouTube, libre de derechos": "YouTube, royalty-free",
    "escala x{n}, píxel perfecto": "x{n} scale, pixel perfect",
    "píxeles nítidos": "sharp pixels",
    "suavizado": "smoothed",
    "todas": "all",
    "{a}: demasiado potente para este escenario": "{a}: too powerful for this stage",
    "¡A luchar!": "Let's fight!",
    "¡Casi lo tienes!": "Almost there!",
    "¡Cuidado con los bichos brillantes! Explotan si se te acercan.": "Watch out for the glowing bugs! They explode if they get close.",
    "¡El Comandante de Élite viene a por ti!": "The Elite Commander is coming for you!",
    "¡Está perdiendo energía! Sigue así, Nexus.": "It's losing power! Keep it up, Nexus.",
    "¡Flota, a mí! ¡Destruidlo!": "Fleet, to me! Destroy him!",
    "¡Gracias por jugar!": "Thanks for playing!",
    "¡Imposible! ¡La señal no te alcanza!": "Impossible! The signal can't reach you!",
    "¡La selva se marchita! Está perdiendo fuerza.": "The jungle is withering! It's losing strength.",
    "¡NUEVO RÉCORD!": "NEW RECORD!",
    "¡Nexus! Te oigo... la señal vuelve. ¡Acaba con él!": "Nexus! I can hear you... the signal's back. Finish him!",
    "¡REFUERZOS!": "BACKUP!",
    "¡SECTOR LIMPIO!": "SECTOR CLEAR!",
    "¡SIN BALAS! Recoge munición o cambia de arma (Q)": "OUT OF AMMO! Pick up ammo or switch weapon (Q)",
    "¡Soldados de a pie! Esos caminan y disparan en línea recta. ¡Salta!": "Foot soldiers! They walk and shoot in a straight line. Jump!",
    "¡Te faltan {n} monedas!": "You need {n} more coins!",
    "¡Toda la Tierra está contigo, soldado!": "All of Earth is with you, soldier!",
    "¡{a} desbloqueada!": "{a} unlocked!",
    "¡{m} nivel {n} desbloqueado!": "{m} level {n} unlocked!",
    "· JUEGO MILITAR ·": "· MILITARY GAME ·",
    "Ártico": "Arctic",
    "Élite roja": "Red Elite",
    "ÓRBITA": "ORBIT",
    "Órbita": "Orbit",
    "Órbita: la Nave Nodriza": "Orbit: the Mothership",
    "Última iniciativa del Ejército Unificado, creada por la doctora Vega bajo el mando del comandante Reyes. Un soldado voluntario con implantes que lo hacen inmune a la señal mental Xylothian. Era el único que podía acercarse a sus líderes sin ser dominado. Nadie esperaba que volviera.": "The Unified Army's last initiative, created by Dr. Vega under the command of Commander Reyes. A volunteer soldier with implants that make him immune to the Xylothian mind signal. He was the only one who could get close to their leaders without being controlled. No one expected him to come back.",
}
